export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikp1bmlvciIsImVtYWlsIjoianVuaW9yMkBlbWFpbC5jb20iLCJpYXQiOjE2ODkxNjEyMTksImV4cCI6MTY4OTc2NjAxOSwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjEifQ.UUHliM4uZgYPXfYuvhA-tGcHwIEJfhZ03isTboAnVI8';
